### ISSUE TITLE
Installation per zip-Folder

### ISSUE THREAD

**Issue by SamuelYaron** [dfki-ric/phobos#1]
If you download the phobos repository via zip file it is named _phobos-master_. Even after renaming it to _phobos_, the blender installation routine via zip file extracts the archive to _phobos-master_.
This causes errors by loading the yaml module, because the script expects the folder to be named phobos. That means installation via zip file is not working in the moment unless you do some stuff manually (renaming the extracted archive after installation).

Is there any known way to alter the name of the donwloaded folder on github or should we rename the path in the script (not recommended)? Or should we dismiss zip installation at all and create a windows installation script too?

**Comment by kavonszadkowski** [comment]
Given the discussions about how to use Phobos in the future (for reference: we're planning to make Phobos usable without having to install it in the first place), this issue will have to stay open until the final decisions on that topic are made.
Then we could also think of making Phobos available via the official Blender add-on website. For the moment, I'd suggest putting up a ZIP with version 0.6.5, as that will be a more stable and user-friendly one than the upcoming 0.6.

**Comment by Amudtogal** [comment]
We have a great solution right now.

**Comment by Amudtogal** [comment]
Installation has so many additional requirements, that we can't satisfy all of them within a zip file (like the yaml installation etc). So we should stick with the single installation method.
