### ISSUE TITLE
Problems working with models and Git

### ISSUE THREAD

**Issue by kavonszadkowski** [dfki-ric/phobos#120]
There is no guideline and no clear strategy on how to use Git or similar SCM tools with Phobos and the models created with it. One of the fundamental problems is that since .blend files are binaries, merges between branches of a model are impossible. Thus changes on the model in blender should only be made in the *master* branch, while it should be possible to export different configurations of a model to other branches. A typical example would be a simplified collision model or a model with a reduced set of joints for specific simulation settings.

Phobos should provide a way to manage these branches, or at least warn the user that a different branch than the *master* branch is checked out while working on the model.

**Comment by Amudtogal** [comment]
We already started implementing git utils for Phobos.
When exporting meshes etc. we should change the branch depending on a user defined setting. We can not use the model version for this, as we can have multiple scenes with different models in a single file.

Should we distinguish branches using different scenes in Blender?

**Comment by AlCap23** [comment]
My current workflow w.r.t to this topic ( as of now ): 

- Checkout merge request
- Export robot
- Use python to merge the files for data like inertials, joint limits, motor parameter etc.
- Add frames / links manual, if the number is small

An automatic approach could be done with URDF / SDF re-import, but SMURF is too generic :).

**Comment by hwiedPro** [comment]
We plan to get rid of the blend file to store model information. Meshes can saved to a submodule/git-lfs/both to keep checkout of binaries quick and the repos small.

**Comment by hwiedPro** [comment]
Solved with [a9aeadf](https://github.com/dfki-ric/phobos/commit/a9aeadfeb0bf130b442f7f0befbac269abb7e2c6)
This script helps configuring git for simulation/control/models by making use of git-lfs.
git-lfs and .gitignore are configured automatically by this script.
