### ISSUE TITLE
Joint vs Motor limits

### ISSUE THREAD

**Issue by kavonszadkowski** [dfki-ric/phobos#123]
Currently joint and motor limits are used in parallel for URDF and SMURF. It needs to be settled if the mechanical limits of joints and the controller limits for motors in terms of range, and the physical limits in terms of speed or torque are different and should be handled thus.

**Comment by Amudtogal** [comment]
In terms of Gazebo/SDF, there is only a joint limit, as motors are not described in their file format.

The question is: in which scenarios would it be required to use motor limits **and** joint limits?

**Comment by Amudtogal** [comment]
I will delete motor limits when reintroducing motors to Phobos.

**Comment by Amudtogal** [comment]
Since I added the motor overhaul, this should be resolved...
