### ISSUE TITLE
File management in SMURF export

### ISSUE THREAD

**Issue by kavonszadkowski** [dfki-ric/phobos#124]
Depending on how the data is structured in the model, standard files of SMURF could be overwritten by generic data if the names overlap. This should be avoided.

Additionally, annotation tags are not cleaned before export and end up in exported files.

**Comment by Amudtogal** [comment]
What can we do about this?

**Comment by AlCap23** [comment]
Set to Phobos 1.1 . Right now, SMURF is not used by many users. Hence the problem can be pushed to our future selfs.

**Comment by hwiedPro** [comment]
This is solved via the merge of pre_v2.0.0 by https://github.com/dfki-ric/phobos/pull/264
