### ISSUE TITLE
Adapt structure of repository to DFKI standards

### ISSUE THREAD

**Issue by kavonszadkowski** [dfki-ric/phobos#133]
This is only for housekeeping and we should do it with the next release, would be too disruptive at the moment.

**Comment by Amudtogal** [comment]
Were are the standards defined?

**Comment by AlexanderFabisch** [comment]
https://wiki.hb.dfki.de/index.php/Standard_Layout

**Comment by Amudtogal** [comment]
We have met all of the possible conditions.

Missing is still the testing/CI (see #121).
This might get interesting in the future, but for now, I will close this as completed.
