### ISSUE TITLE
Scale messes up collision position

### ISSUE THREAD

**Issue by hwiedDFKI** [dfki-ric/phobos#135]
If a visual is scaled, the collision is created with the correct dimensions but the location remains with scale (1,1,1). Therefore the collision is placed somewhere else.

**Comment by hwiedDFKI** [comment]
Apply scale solves this

**Comment by kavonszadkowski** [comment]
That may be the case, but at least for meshes it should be possible to keep a scale. Goes on the list of bugs to fix before the next release.
