### ISSUE TITLE
Wish for next release: Give Materials a density property

### ISSUE THREAD

**Issue by hwiedDFKI** [dfki-ric/phobos#136]
Masses can then be calculated via volume.
Volume functions are implemented in VolumeTools or 3D Print Toolbox

**Comment by kavonszadkowski** [comment]
Since most input for Phobos comes from CAD, this is likely problematic, as CAD *never* produces a "well defined mesh", i.e. one without holes. I'm not even sure how `Operators` such as `Edge Split` influence this.

**Comment by Amudtogal** [comment]
I would say this feature is too niche to be useful (even more, it may confuse users, as it would only work with primitives).
If there is sufficient need for this to be implemented, we could add it as a supplement script...
