### ISSUE TITLE
Please fix FIXME in phobos/model/links.py:73

### ISSUE THREAD

**Issue by hwiedDFKI** [dfki-ric/phobos#138]
This results in problems when trying to export a model with renamed links

**Comment by kavonszadkowski** [comment]
This relates to a greater issue in name handling within Phobos, as many cross-references are still done with names. We want to fix that system with the upcoming 1.0.

**Comment by Amudtogal** [comment]
There is no such FIXME in the mentioned file, so I guess this was fixed.

Otherwise, please point to the respective function (as line numbers change rapidly in active software development) and reopen this issue.
