### ISSUE TITLE
SDF integration for Phobos

### ISSUE THREAD

**Issue by hwiedDFKI** [dfki-ric/phobos#142]
Add option to write model.config together with sdf. 
Format:

```
<?xml version="1.0" ?>
<model>
    <name>$MODEL_NAME</name>
    <version>1.0</version>
    <sdf version="1.5">$MODEL_NAME.sdf</sdf>
    <author>
        <name>$AUTHOR_NAME</name> <!--get via query or e.g. git author-->
        <email>$EMAIL</email>
    </author>
    <description>$DESCRIPTION</description> <!--Suggestion: could be added in a README, too-->
</model>
```

**Comment by Amudtogal** [comment]
We should also add some kind of a scene export for the SDFormat.
This would also allow us to add robot submodels as model elements to a world.

However, to generate valid SDF models, the model should be exported to a single folder (which needs to contain the meshes, too). My suggestion:
Let's add the Gazebo model folder as a setting to Phobos, so we can export models there (and maybe even load models from it!).
