### ISSUE TITLE
Generic entity export

### ISSUE THREAD

**Issue by Amudtogal** [dfki-ric/phobos#157]
While cleaning up the repo I found this stale branch:

[defineEntity](https://github.com/dfki-ric/phobos/tree/dev/defineEntity)

As I could not guess the feature of this branch, I open this discussion on whether the feature of this branch shall be included into Phobos, or is already.

@sklemp29 What are the exact changes of this branch and are they finished?

**Comment by hwiedPro** [comment]
Considering this branch as to old to be included.
