### ISSUE TITLE
How to hide inertia after importing URDF?

### ISSUE THREAD

**Issue by Guptajakala** [dfki-ric/phobos#168]
This add-on is awesome, Im using it as part for my next research paper. However, after importing URDF file, the intertial will appear as a separate object and looks a cube. It still appear during rendering. Is there anyway to hide them?

**Comment by Amudtogal** [comment]
If you use the **Sort Objects to Layers** operator under general tools, you will have the visuals, links etc sorted to Blender layers.

Render without showing the layers you don't need. Good luck with your paper!
