### ISSUE TITLE
Artifacts from a failed merge in the Wiki

### ISSUE THREAD

**Issue by CameronDevine** [dfki-ric/phobos#179]
The following pages in the Wiki have artifacts (`<<<<<<< HEAD` etc.) from an incomplete merge.

* [Kinematic Skeleton](https://github.com/dfki-ric/phobos/wiki/Kinematic-Skeleton)
* [Modeling Walkthrough](https://github.com/dfki-ric/phobos/wiki/Modeling-Walkthrough)
* [Model Validation](https://github.com/dfki-ric/phobos/wiki/Model-Validation)
* [Motors](https://github.com/dfki-ric/phobos/wiki/Motors)
* [Operators](https://github.com/dfki-ric/phobos/wiki/Operators)
* [Phobos GUI](https://github.com/dfki-ric/phobos/wiki/Phobos-GUI)
* [Robot Dictionary](https://github.com/dfki-ric/phobos/wiki/Robot-Dictionary)
* [Poses](https://github.com/dfki-ric/phobos/wiki/Poses)
* [Scenes](https://github.com/dfki-ric/phobos/wiki/Scenes)
* [Scripting](https://github.com/dfki-ric/phobos/wiki/Scripting)
* [Structure of Robot Models](https://github.com/dfki-ric/phobos/wiki/Structure-of-Robot-Models)

**Comment by Amudtogal** [comment]
I have fixed the merge conflicts, however there are still some TODOs that need to be fixed...
