### ISSUE TITLE
Add numpy on required python packages

### ISSUE THREAD

**Issue by gstavrinos** [dfki-ric/phobos#182]
Numpy is required for phobos to work properly, which is not mentioned in the Installation wiki. Only PYaml is mentioned.

**Comment by Amudtogal** [comment]
`numpy` is part of the Blender internal python, so it should be included without any hassle.

If you experience any issue, could you please include the error messages and especially Blender version and OS?

**Comment by gstavrinos** [comment]
Hey @Amudtogal, I have no longer access to the error, but was the typical "module not found" python error. I use the recommended blender version and MX Linux 18.1 (essentially Debian stretch). I ran `pip3 install numpy` and the error was solved. Keep in mind that the error occured when I tried to include the add-on through user preferences, and not during setup. After I installed numpy, I rerun setup.py (just to be sure) and after that I could include the add-on normally.

**Comment by Amudtogal** [comment]
Hey @gstavrinos,
I just added `numpy` to the dependencies in the installation section.
We had the same issue in #183. Apparently, some Debian versions of Phobos are not compiled with `numpy` included. Thanks for your bug report and happy blending!
