### ISSUE TITLE
not appearing in toolbar panel

### ISSUE THREAD

**Issue by PakoYam** [dfki-ric/phobos#184]
**Describe the bug**
After installing and enabling, phobos does not appear on the toolbar panel.

1. I have followed the installation manual from https://github.com/dfki-ric/phobos/wiki/Installation

2. After running the code "py -3 setup.py", it didn't ask me anything about my Blender version. 

3. I opened Blender, the add-on is already enabled automatically in User Preferences. But nothing appears on the toolvar panel (see Screenshot 1).

4. If I disable it and try to enable it again, it returns an error. (see Screenshot 2).

**Screenshots**
Screenshot 1:
![Screenshot1](https://user-images.githubusercontent.com/18424565/58699628-3cd25700-839e-11e9-9586-0912ea2c7d28.jpg)

Screenshot 2:
![Screenshot2](https://user-images.githubusercontent.com/18424565/58699781-a6eafc00-839e-11e9-817b-4e9cecfbbefa.jpg)

**Desktop (please complete the following information):**
 - Windows 10
 - Blender version: 2.79b
 - Blender Python version 3.5.3

Thank you.

**Comment by Amudtogal** [comment]
Hi PakoYam,
at first, thanks for your bug report!

Let us try some steps first:
- the main issue is the missing yaml installation (that actually caused your problem). Could you check whether `yaml` can be imported from your python console (search for python in your windows searchbar and either start *IDLE Python* or the *Python Interpreter*).
 - it is surprising, that Phobos was already enabled in your settings. Did you have Phobos on your computer before? Did you use the `--startup-preset` option when installing? Anyway, try removing the phobos folder from your **HOMEFOLDER**`/AppData/Roaming/Blender Foundation/Blender/2.79/scripts` path (you might need to enable hidden files to see it). Then remove the `python_dist_packages.conf` from your Phobos download folder. After this, Phobos should be removed when starting Blender. A subsequent reinstall might fix the issue...

Can you check these steps?
Best,
Amudtogal

**Comment by Amudtogal** [comment]
I assume this was resolved, otherwise please reopen...
