### ISSUE TITLE
Motor coversion script fails for motor type DC

### ISSUE THREAD

**Issue by georgeslabreche** [dfki-ric/phobos#185]
**Describe the bug**
A `KeyError` is thrown when the [phobos_convert_motor_pre_1_0.py](https://github.com/dfki-ric/phobos/blob/release-1.0/templates_py/phobos_convert_motor_pre_1_0.py) script attempts to map _motor/type_ DC to _generic_dc_.

**To Reproduce**
1. Clone the [SherpaTT model repo](https://git.hb.dfki.de/facilitators/sherpa_tt.git).
2. Open the SherpaTT model in Blender.
3. In Layer 0 for Links (Joints), select one of the joints that has _motor/type_ DC (e.g. omega_front_right).
4. Run the script.

**Expected behavior**
Motor and motor controller will be created for the selected DC motor joint.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04
 - Blender version: 2.79b
 - Blender Python version: 3.6.7

**Additional context**
As per [defaultMotors.yml](https://github.com/dfki-ric/phobos/blob/release-1.0/config/definitions/defaultMotors.yml), only the following motors are supported by MARS:
- generic_dc
- generic_bldc
- limes_typ1
- limes_typ2
- limes_typ3

However, the script fails to map _motor/type_ DC to _generic_dc_ because the `derive_oldMotor(obj) ` function lacks the `elif` statement to handle _motor/type_ DC. See here:

https://github.com/dfki-ric/phobos/blob/release-1.0/templates_py/phobos_convert_motor_pre_1_0.py#L23-L26

The proposed fix is to include an `elif` statement for DC:

```
if oldProps == 'motor/type' and obj[oldProps] == 'PID':
    new_motor.update({newProps: 'generic_bldc'})
elif oldProps == 'motor/type' and obj[oldProps] == 'DC':
    new_motor.update({newProps: 'generic_dc'})
else:
    new_motor.update({newProps: obj[oldProps]})
```

**Comment by AlCap23** [comment]
Solved via 8811692b4b6aa9fc3cd04bc2082ce11b2ca025a5
