### ISSUE TITLE
Motor conversion script does not create motors and controllers in expected layer.

### ISSUE THREAD

**Issue by georgeslabreche** [dfki-ric/phobos#186]
**Describe the bug**
The [motor conversion script](https://github.com/dfki-ric/phobos/blob/release-1.0/templates_py/phobos_convert_motor_pre_1_0.py) does not create motors and controllers in the expected layer 4 as per the [Phobos documentation](https://github.com/dfki-ric/phobos/wiki/Structure-of-Robot-Models#model-composition-and-layers).

**To Reproduce**
1. Clone the [SherpaTT model repo](https://git.hb.dfki.de/facilitators/sherpa_tt.git).
2. Open the SherpaTT model in Blender.
3. In Layer 0 for Links (Joints), select all links.
4. Run the script.

**Expected behavior**
Motor and controllers are created in layer 4.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04
 - Blender version: 2.79b
 - Blender Python version: 3.6.7

**Additional context**
The layer assignment convention given in the [Phobos documentation](https://github.com/dfki-ric/phobos/wiki/Structure-of-Robot-Models#model-composition-and-layers) is as follow:

- Layer 0: Links (Joints)
- Layer 1: Inertials
- Layer 2: Visuals
- Layer 3: Collisions
- Layer 4: Sensors / Controllers

However, running the script split layer 4 across [layers 4, 7, and 8](https://github.com/dfki-ric/phobos/blob/release-1.0/phobos/defs.py#L39-L53)

Further disaggregating between sensors, controllers, and motors does make sense so it could it be that the real issue is that the Phobos documentation is not up to date.

**Comment by AlCap23** [comment]
Hi Georges,

the motors and motorcontroller are moved to layer 7 and 8. The documentation needs indeed to be updated regarding that. Sensors are based on layer 4 and their corresponding annotation ( the information for the export , e.g. smurf or sdf , is found on layer 15.
