### ISSUE TITLE
Exporting a model results in duplicated visual mesh.

### ISSUE THREAD

**Issue by georgeslabreche** [dfki-ric/phobos#187]
**Describe the bug**
At some point during the export, one of the visual objects selected for export gets duplicated. The duplicate is positioned at the center of the scene and is half the scale of the original.

**To Reproduce**
This can be reproduced by exporting the latest sherpa_tt model in master (internal dfki repo):
1. Open the sherpa_tt model in Blender.
2. Run the select_for_export.py script.
3. Export.

**Expected behavior**
The export should occur without any objects being duplicated in the scene.

**Screenshots**
Here is a screencast of the issue:

![mesh-duplication](https://user-images.githubusercontent.com/1258236/61128652-c9e6f080-a4b2-11e9-9af1-f9e30e023da9.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04
 - Blender version: 2.79b
 - Blender Python version: 3.6.7

**Additional context**
When running the export on MARS, the visual mesh that was duplicated is not rendered (at least where it is meant to be).

This bug is consistently reproducible at every export but can be stopped if the affected mesh is replaced with a new copy. However, this "fix" is only temporary and the issue eventually manifests itself again either with the same mesh or with a more recently created one.

**Comment by hwiedPro** [comment]
As this issue is quite old uses a custom python script. I close this for now. Please reopen the issue if this issue persists, with the latest phobos:develop vresion
