### ISSUE TITLE
When exporting to urdf the properties of mimicked joints/motors are not included in the *_motors.yml file.

### ISSUE THREAD

**Issue by georgeslabreche** [dfki-ric/phobos#189]
**Describe the bug**
Mimicked motors are not included in the *_motors.yml file after exporting to urdf. Instead, a *_motor.yml (unpluralized) file is produced with the mimic properties under `link` and `joint` categories. Mimicking does not work with these yml files when loading the model in MARS.

**To Reproduce**
1. Define a joint, motor, and motor controller.
2. Mimic the joint and the motor created in the previous step.
3. Select all objects and export to urdf.

**Expected behavior**
The definition of the motor mimic in *_motors.yml should have the following properties:
- mimic_motor
- mimic_multiplier
- mimic_offset

**Screenshots**
Something like this is expected in the *_motors.yml:

![image](https://user-images.githubusercontent.com/1258236/61731056-f1736e00-ad7a-11e9-969d-1084d56ad6bf.png)

Instead, we get something like this without the mimic properties:

![image](https://user-images.githubusercontent.com/1258236/61731212-4adb9d00-ad7b-11e9-97a8-c18ab90dc987.png)

And the missing mimic properties are located in another file, *_motor.yml (unpluralized), under `link` and `joint` categories:

![image](https://user-images.githubusercontent.com/1258236/61731470-d7865b00-ad7b-11e9-9ece-e90d6a452e29.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04
 - Blender version: 2.79b
 - Blender Python version: 3.6.7

**Additional context**
The *_motor.yml (unpluralized) file is created in the [`exportSmurf`](https://github.com/dfki-ric/phobos/blob/f4975f185eed648f4ddce8aec8af0a0e68fe8f33/phobos/io/entities/smurf.py#L189-L542) function and represents [_"additional information"_ that is being written in its own file](https://github.com/dfki-ric/phobos/blob/f4975f185eed648f4ddce8aec8af0a0e68fe8f33/phobos/io/entities/smurf.py#L409-L421). This _additional information_ is retrieved via [`models.gatherAnnotations(model)`](https://github.com/dfki-ric/phobos/blob/f4975f185eed648f4ddce8aec8af0a0e68fe8f33/phobos/model/models.py#L1283-L1339) which is [invoked here](https://github.com/dfki-ric/phobos/blob/f4975f185eed648f4ddce8aec8af0a0e68fe8f33/phobos/io/entities/smurf.py#L242).

There seems to be a step missing when [processing the motors data](https://github.com/dfki-ric/phobos/blob/f4975f185eed648f4ddce8aec8af0a0e68fe8f33/phobos/io/entities/smurf.py#L300-L340) in which the _additional information_ dictionary should be checked for mimic motor related data to be included when [writing the *_motors.yml file](https://github.com/dfki-ric/phobos/blob/f4975f185eed648f4ddce8aec8af0a0e68fe8f33/phobos/io/entities/smurf.py#L376-L388).

Also, when mimicking a joint in Phobos and checking the mimic motor option, no motor or motor controller is created. Is this normal? Is the motor mimicking only meant to be via joint properties?

**Comment by AlCap23** [comment]
Should be fixed for SMURF with 798256ca0f076d2f8aa891a2a62dd88d216c9870
