### ISSUE TITLE
Tutorial video

### ISSUE THREAD

**Issue by innokaiclub** [dfki-ric/phobos#193]
Is this repo still active? If so, may i request a tutorial video

**Comment by Amudtogal** [comment]
Hi there,
this repository is indeed still active, and we also recorded some tutorial videos already.
However those will be put online earliest in a few months from now (we need to find some time for doing the editing).
Until then, you can get a great overview using our [Wiki](https://github.com/dfki-ric/phobos/wiki) and the [API documentation](http://dfki-ric.github.io/phobos/)
Feel free to come back with things you don't understand, so we can resolve this and also adjust the Wiki :smile:
