### ISSUE TITLE
Can't activate phobos addon in Linux Deepin os.

### ISSUE THREAD

**Issue by Sumon-miazi** [dfki-ric/phobos#198]
I follow the procedure which is given in the installation wiki [https://github.com/dfki-ric/phobos/wiki/Installation](url) . And I am using deepin os and have python3.5.

and my addon page shows this error informations:-
![DeepinScreenshot_select-area_20191102234429](https://user-images.githubusercontent.com/28239287/68074946-9c101980-fdcb-11e9-966f-a88ecdc1310b.png)

and I downloaded the latest release version but my version number is pointing to 0.7.1. Is this ok?
![DeepinScreenshot_select-area_20191102234554](https://user-images.githubusercontent.com/28239287/68074962-c8c43100-fdcb-11e9-9a69-b4ed6ea22994.png)

How can I solve this? help, please...

**Comment by Amudtogal** [comment]
Could you retry on the new release?

We changed the installation, so this might have resolved your issue...

**Comment by Amudtogal** [comment]
I assume this is resolved, otherwise please reopen...
