### ISSUE TITLE
Suggestion: better installation of dependencies

### ISSUE THREAD

**Issue by Pouya-moh** [dfki-ric/phobos#200]
Hi, and thanks for great add-on.

The wiki suggests to install `PyYaml` via system `pip`. The problem is, and might be wrong here as I am no python expert, `pip` installs in `~/.local/lib` and this might not be in blender's path.

A possible alternative is to use Blender's python pip to install yaml as described [here](https://blender.stackexchange.com/a/140343/53761). In my 2.79 for instance:

```
cd blender-home/2.79/python/bin
./python3.5m -m ensurepip
./python3.5m -m pip install --upgrade pip
./python3.5m -m pip install PyYaml
```
This could solve any `ImportError: No module named 'yaml'` type of error. Maybe...

**Comment by Amudtogal** [comment]
I really like the idea!

We have been messing with the installation for quite a while (it works atm, but not really safe).
I am trying to incorporate it into our current installation procedure...
