### ISSUE TITLE
Export one Armature/Skeleton

### ISSUE THREAD

**Issue by hawkina** [dfki-ric/phobos#203]
Hey
I'm looking into importing an ROS urdf into blender in order to create a Skeleton/Armature from the robot so that I can import it into e.g. Unreal Engine. It seems that currently with phobos I do get the urdf imported but I get many armatures, each containing one Bone. 
Is there a way to quickly create one Armature only from this? Am I overlooking something or is this just currently not possible?

Kind regards, 
Hasu

**Comment by Amudtogal** [comment]
Dear Hasu,
this is a design choice of us, which reaches a long way back...
Picking an armature each as a reference object for links in a URDF file allows us to manipulate the object visually and also use many features of Phobos more flexible (such as batch renaming). Bones within Blender's armatures are coded differently and the Blender API handles them in a different manner.

I think there might be a way of joining the armatures while keeping the parenting hierarchy of them, but this is more of a Blender question... Also, attaching the different collision objects to the single armature would work differently.

I have no idea how you would export an armature for Unreal Engine, so I can not help you further than this...

Kind regards,
Simon
