### ISSUE TITLE
Installation on MacOS

### ISSUE THREAD

**Issue by artificial-cassiano** [dfki-ric/phobos#206]
Hi, 
thanks for this super useful plugin!

When I try to install on MacOS (OSX Catalina) by running:
`python3 setup.py --blender /Applications/`
I get this following error message: 
`Could not identify the blender subfolder.
Installation aborted!`

on Mac Blender (2.8) is installed as an app on `/Applications/Blender.app`, not a directory. How should I pass this argument to setup.py?

thanks

**Comment by malter** [comment]
Hey,

I have a open pull request which includes some notes for installing Phobos on MacOS:
https://github.com/dfki-ric/phobos/pull/204/commits/4d64775bb4a49fcc2b2e922456df884a92be80c1

By the way, Phobos is currently not compatible with Blender 2.8, to use Phobos you should also install Blender 2.79.

**Comment by Amudtogal** [comment]
I will work on this issue (and the pull-request) this weekend!

Currently on a conference :)

**Comment by Amudtogal** [comment]
I have updated (but not yet pushed) the setup.py to work on macOS as well.
Right now, I am hunting down someone around here, to test it before I push.
Expect it this afternoon...

**Comment by Amudtogal** [comment]
Could you check the new installation, and in particular the [macOS section](https://github.com/dfki-ric/phobos/wiki/Installation#macos-1) in the wiki?

Before reinstalling, please remove the installation.conf file first and make sure you installed Blender 2.79, as described in the wiki.

Regards

**Comment by Amudtogal** [comment]
I assume this is fixed, otherwise reopen.
