### ISSUE TITLE
Error while trying to create a joint

### ISSUE THREAD

**Issue by ahgartner** [dfki-ric/phobos#208]
Hello,

I was going through the tutorial to add kinematics to my model and then when I tried to create a joint, this error occured and my model disappears. Only after I click a node, my model appears again.
Could you please help me?
<img width="386" alt="phobos_error" src="https://user-images.githubusercontent.com/65547238/82216658-8f8f8080-9919-11ea-8d6d-221f06d49645.png">

I am working on Windows 10, Blender 2.79b.

Thanks in advance!

**Comment by kavonszadkowski** [comment]
Most of the work on and with Phobos has been done on Linux and this bug seems to stem from the assumption that the resource files are always in the same place. Which I suspect they are not under Windows. I'll have to look into it.

**Comment by hwiedDFKI** [comment]
This could be solved by blenders bpy.utils.user_resource.
@kavonszadkowski Do you have updates?

**Comment by malter** [comment]
I think we should try to reproduce the bug in the current master version. Maybe with the current Blender version on Windows it is already solved. I can try that out next week.

**Comment by hwiedPro** [comment]
Couldn't reproduce in the current version. Please reopen if this persists for you.
