### ISSUE TITLE
Supporting/Donating for the project

### ISSUE THREAD

**Issue by Xia0ben** [dfki-ric/phobos#215]
**Is your feature request related to a problem? Please describe.**
I could not find any donation link to help the project move forward, and would especially like to donate to support efforts in bringing and keeping Phobos up to speed with the new Blender versions.

**Describe the solution you'd like**
A donation system via Liberapay, Issuehunt, Patreon or whatever, as long as it's possible to help the project when you can't contribute dev time, so that as much as possible of the money goes to the devs and not the intermediary platform.

**Describe alternatives you've considered**
I have no idea. Would sending homemade cookies by mail to the phobos contributors be of any help in moving things forward ? =)

**Additional context**
When I saw today @malter 's contributions to help bring Phobos to Blender 2.9, this drove me to write this message.

Thank you very much for your attention.

**Comment by hwiedPro** [comment]
Hi @Xia0ben,

thanks a lot that you like Phobos that much, and thanks that you want to give donations.
As Phobos is developed as part of different funded projects our work already gets paid, even though not with cookies. ;P

The best donation you can give us is telling others how much you like Phobos and that they should use it, too. :)

Thanks again and all the best!
