### ISSUE TITLE
Support upbge - add support for BT_Multi_body() 

### ISSUE THREAD

**Issue by BluePrintRandom** [dfki-ric/phobos#216]
**Is your feature request related to a problem? Please describe.**
upbge has bullet physics engine - but BT_MultiBody is not currently wrapped 

**Describe the solution you'd like**
wrap BT_Multibody in upbge and list it as a target

**Additional context**
https://www.youtube.com/watch?v=XeeYf1HHxeY - UPBGE is a robust physics environment coupled with a realtime python api

**Comment by hwiedDFKI** [comment]
Could you please elaborate on what exact feature/ability you expect us to add?

But according to your video: Phobos is a tool to annotate Robot models exported from CAD to prepare it for simulation, not to simulate/animate the model directly in Blender. Therefore I label it for the time being as wontfix. If I got you wrong and you elaborate your request further I'll update.

**Comment by hwiedPro** [comment]
This seems to be stale. Please reopen otherwise
