### ISSUE TITLE
How to create the relationship of two rotating gears

### ISSUE THREAD

**Issue by mn-banjar** [dfki-ric/phobos#217]
Hi, I'm trying to use this plugin to create urdf file of a robot arm.
How to configure two rotating gears?

**Comment by malter** [comment]
Hi, I'm sorry I didn't get the question right away. The [Modeling Walkthroug](https://github.com/dfki-ric/phobos/wiki/Modeling-Walkthrough) describes the way you can model a robot arm in general. But what kind of configuration do you mean with two rotating gears? Normally, for each driven rotating axis you create a joint and a motor in urdf. You can create joints without motors for passive DOFs and you can use mimic joints to clone movements between joints.

**Comment by mn-banjar** [comment]
> Hi, I'm sorry I didn't get the question right away. The [Modeling Walkthroug](https://github.com/dfki-ric/phobos/wiki/Modeling-Walkthrough) describes the way you can model a robot arm in general. But what kind of configuration do you mean with two rotating gears? Normally, for each driven rotating axis you create a joint and a motor in urdf. You can create joints without motors for passive DOFs and you can use mimic joints to clone movements between joints.

Thank you I solved the issue
yes, It was about using mimic joints
Actually, I wrote the tag by hand on the urdf file
