### ISSUE TITLE
Export location bug?

### ISSUE THREAD

**Issue by AzulRadio** [dfki-ric/phobos#218]
A bug that occurs when I try to export from a saved .blend file.

In short: Phobos exports to the wrong folder.

1. save a .blend file in a folder, say that, /home/Desktop/folder1/folder2/file.blend
2. open the .blend file, the default export path is ../
3. click the folder icon on the right of the "path: ", it always shows /home
4. say that we choose to export to /home/Desktop, click "accept"
5. the path now becomes "path: ../Desktop", but phobos will create a folder named "Desktop" in the upper directory of my .blend file and export everything there, instead of the real Desktop. That is /home/Desktop/folder1/Desktop/file.urdf

I guess the problem is ../ gives you the directory of the folder I installed blender (Yes. I install it in /home) but phobos exports based on the location of the saved .blend file.

I'm on Ubuntu 18.04, phobos 1.0.1, and blender 2.79. 

Thanks for helping in advance! Phobos is a really useful add-on and thanks to everyone contributing to it!

**Comment by hwiedPro** [comment]
This is solved for v2.0.0. Therefore I close this issue now.
