### ISSUE TITLE
Failed to install on Ubuntu 20.04  with 'Could not identify the blender subfolder.'

### ISSUE THREAD

**Issue by antoan** [dfki-ric/phobos#221]
**Describe the bug**
Cloned the repo and checked out release 1.0
Then from the phobos directory I attempted to install to my system blender installation /usr/share/blender (where the addon folder is located): 
 
```
~/dev/phobos$ python3 setup.py --startup-preset --blender /usr/share/blender/
Could not identify the blender subfolder.
Installation aborted!
```

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04.1 LTS x86_64 
   Kernel: 5.8.0-38-generic

**Comment by Roboticistprogrammer** [comment]
@antoan Can you share how you solved the problem?
