### ISSUE TITLE
Not able to import and work with stl files

### ISSUE THREAD

**Issue by gautam-sh** [dfki-ric/phobos#223]
**Describe the bug**
I am able to import stl file but then it is imported as a single element. Hence I am not able to select different components as different links to proceed further. And it gets killed automatically after some time.

**To Reproduce**
Import stl file.

**Expected behavior**
Model for editing and creating urdf file.

**Screenshots**
![Screenshot from 2021-03-24 14-12-13](https://user-images.githubusercontent.com/45528077/112280642-387dd900-8cab-11eb-89c7-d4e886d8fe89.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

While adding the addon I also opted for the option to modify default blender settings as mentioned in the installation instructions.

Also while trying to edit, I am getting this
```
location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/gautam/.config/blender/2.79/scripts/addons/phobos/operators/editing.py", line 561, in execute
    eUtils.removeProperties(obj, [self.property_name])
  File "/home/gautam/.config/blender/2.79/scripts/addons/phobos/utils/editing.py", line 700, in removeProperties
    elif prop[-1] == '*':
IndexError: string index out of range

location: <unknown location>:-1
```

**Comment by malter** [comment]
Just to get it right: You import a single STL file and then want to model your robot by adding links, collisions, etc.?
And in your case the STL import of Blender creates a single object?
If I got it right, in the first place you have two options:
  1. Check the source of the STL and if it is possible to change the export option, like exporting single STL for single components
  2. If that is not possible, you have to switch into Blender "edit-mode" and separate the objects manually. Depending on the model this can require more or less effort. In many cases you can select a single vertex in edit-mode and type "Ctrl-L" to select all linked vertices which represent one complete components, if you are lucky.

Hope that helps a bit.

Concerning the crash I didn't get when it is happening. Maybe Blender becomes unstable if the model is too large. Or does it happen while you where working with the Phobos tools?

**Comment by malter** [comment]
Closed due to no feedback
