### ISSUE TITLE
Cannot import urdf: AttributeError: 'NoneType' object has no attribute 'attrib'

### ISSUE THREAD

**Issue by zxubian** [dfki-ric/phobos#224]
**Describe the bug**
Importing a urdf produces this error:

AttributeError: 'NoneType' object has no attribute 'attrib'

**To Reproduce**
* Open Python
* Enable phobos in settings
* In phobos panel, click import robot
* Select .urdf description file

**Expected behavior**
Import urdf

**Screenshots**

![image](https://user-images.githubusercontent.com/8446683/112569927-6a687a00-8e28-11eb-8034-4692d9823111.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender is installed to C:\Blender

**Comment by malter** [comment]
Hey,

when you click on import model and get to the point to select the file for the import, there is a small select box on the lower left corner of blender. There you can select to import a sdf or urdf model and it looks like sdf was selected in your case?

Best
