### ISSUE TITLE
Cannot export joint damping to URDF

### ISSUE THREAD

**Issue by Spike87** [dfki-ric/phobos#225]
**Describe the bug**
When setting "damping constant" when defining a joint, this property does not show up in the URDF tags of the joint.

**To Reproduce**
1. Select joint (right click)
2. Click on 'Define joint(s)'
3. Set 'damping constant' to 0.2
4. Select robot hierarchy
5. Click on 'Export model'
6. No 'dynamics damping' tag shows in the URDF file

**Expected behavior**
When setting "damping constant" when defining a joint, the 'dynamics damping' tag should show up in the URDF file.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.2 LTS
- Blender version: 2.79b
- Phobos version: 1.0.1

**Comment by hwiedDFKI** [comment]
We are aiming to have this included in the next major release on which we are working at the moment. Thanks for your patience.

**Comment by hwiedPro** [comment]
This is solved for v2.0.0. Therefore I close this issue now.
