### ISSUE TITLE
phobos/operators/editing.py#L3515 models isn't defined

### ISSUE THREAD

**Issue by Islam0mar** [dfki-ric/phobos#227]
models isn't defined here [models.deriveModelDictionary(root)](https://github.com/dfki-ric/phobos/blob/master/phobos/operators/editing.py#L3515)

It worked after adding `from phobos.model.models import deriveModelDictionary` and change the previous line to `model = deriveModelDictionary(root)`, but I haven't found others reporting the same error!!!

I tried master as well as release-1.0 branch.

**Comment by malter** [comment]
Fixed on master and blender2.9 branches
