### ISSUE TITLE
I can't start anything

### ISSUE THREAD

**Issue by HoangGiang93** [dfki-ric/phobos#235]
**Describe the bug**
How do I install the add-on? It doesn't work with any blender version.

**To Reproduce**
1. Follow wiki

**Expected behavior**
Nothing works, always the same error
```
fake_module: addon missing 'bl_info' gives bad performance!: '/home/giang/.config/blender/2.79/scripts/addons/setup.py'
```
**Screenshots**
![Screenshot from 2022-03-20 19-16-36](https://user-images.githubusercontent.com/64316740/159176625-c883777f-a2f7-489b-b7e0-d2f05df13b1f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04 
 - run `setup.py --info`: some branch doesn't even have setup.py
 
 **Suggestion:**
 Please provide an installation video, it's much more easier to follow

**Comment by malter** [comment]
Hey, we had some trouble with switching to the new Blender version. I would suggest to not use a release version but the master branch instead with Blender 2.93 and follow this install steps: https://github.com/dfki-ric/phobos#installation

**Comment by HoangGiang93** [comment]
Thanks
