### ISSUE TITLE
Cannot import urdf

### ISSUE THREAD

**Issue by 1seck** [dfki-ric/phobos#244]
Hi there,

I am running phobos on Blender 2.93.8 and managed to install phobos.
I can see the menus "Phobos Matrix information", "Phobos Property information" and "Model Warnings" but nothing else.
How can I import a urdf file? 
I cannot see any phobos "main menu" or alike?
I installed from master branch.

start console output:

> Importing phobos
> IMPORT:  phobos.defs
> Parsing definitions from: /Users/*/Library/Application Support/Blender/2.93/scripts/addons/phobos/config/definitions
>   defaultSubmodels.yml
>   defaultMotors.yml
>   defaultMaterials.yml
>   defaultControllers.yml
>   defaultSensors.yml
>   defaultJoints.yml
>   defaultModel.yml
>   defaultSubmechanisms.yml
> Creating new definition type: joints
> IMPORT:  phobos.display
> IMPORT:  phobos.io
> Registered mesh plugin: ['obj', 'stl', 'dae']
> ERROR in scenes/__init__: "mars.py" has no valid scene plugin interface.
> Registered scene plugin: ['sdf world']
> Registered scene plugin: ['smurfs']
> Registered entity plugin: ['smurf']
> ERROR in entities/__init__: "heightmap.py" has no valid entity plugin interface.
> Registered entity plugin: ['light']
> Registered entity plugin: ['thumbnails']
> Registered entity plugin: ['yaml']
> Registered entity plugin: ['srdf']
> Registered entity plugin: ['primitive']
> Registered entity plugin: ['sdf']
> Registered entity plugin: ['urdf']
> Registered entity plugin: ['submechanisms']
> Registered entity plugin: ['generic']
> Registered mesh plugin: ['obj', 'stl', 'dae']
> ERROR in scenes/__init__: "mars.py" has no valid scene plugin interface.
> Registered scene plugin: ['sdf world']
> Registered scene plugin: ['smurfs']
> RELOAD:  phobos.model
> IMPORT:  phobos.operators
> IMPORT:  phobos.phobosgui
> RELOAD:  phobos.phoboslog
> RELOAD:  phobos.phobossystem
> RELOAD:  phobos.utils
> Registering operators.selection... 
> Registering operators.io...
> Registering operators.editing...
> Registering operators.naming...
> Registering operators.misc...
> 
> Registering phobosgui...
>   ... successful.
> 

Regards

**Comment by 1seck** [comment]
ok got it

**Comment by llamcpp** [comment]
where? i cant seem to find it too

**Comment by hwiedPro** [comment]
There has been added a hint in the README ;)
