### ISSUE TITLE
Layout of the readme is not always good

### ISSUE THREAD

**Issue by AlexanderFabisch** [dfki-ric/phobos#248]
**Describe the bug**
Layout in readme is not always good.

**To Reproduce**
1. Go to main GitHub page of phobos
2. Scroll down to readme
3. Change size of the browser window

**Expected behavior**
There should be a line break before the image

**Screenshots**

![Screenshot_20220802_092355](https://user-images.githubusercontent.com/869592/182316811-14b9a885-8503-42c4-9013-aa123d84c1e5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: firefox

**Comment by malter** [comment]
Fixed and thanks for the hint! :-)
