### ISSUE TITLE
phobos is not showing in blender addon

### ISSUE THREAD

**Issue by Omar2664** [dfki-ric/phobos#251]
I installed phobos in blender addon 
and file exist   ~/.config/blender/2.82/scripts/addons/phobos

but not showing in blender addon
![Screenshot from 2022-08-15 21-20-22](https://user-images.githubusercontent.com/108147024/184695415-b882f5f7-bfc1-4f85-8a02-236b544524c9.png)
n

NOTE: using Oracle VM Virtulbox: Linux

**Comment by hwiedPro** [comment]
Hi thanks for your issue.
Can you show the output of `ls ~/.config/blender/2.82/scripts/addons/phobos` please?

**Comment by hwiedPro** [comment]
I guess this is solved. If not, feel free to reopen.
