### ISSUE TITLE
Exporting to fbx gives a completely messed up mesh and bones

### ISSUE THREAD

**Issue by tomkimsour** [dfki-ric/phobos#258]
I imported my urdf, rescaled the meshes and move two of them to the correct position because there is an error in the urdf.
Afterwards I selected the meshes and armature to export it in fbx with the default values. 

On the right is the armature from my import and on the left is the one from the exported fbx file.
![Screenshot from 2022-09-14 10-44-20](https://user-images.githubusercontent.com/48397347/190036695-533eaa6b-524e-4552-a030-a3e39e561242.png)

Hierarchically, the armature makes sense, however some axes are in the wrong direction and some were even added.

**Comment by hwiedPro** [comment]
Hi thanks for your interest in using phobos and your feature request #259. Currently phobos is only used for editing robotic simulation & control models, support for animation/gaming purposes including fbx conversion is not yet planned. However we are open for contributions there.

Let's continue the discussion in #259
