### ISSUE TITLE
Error when set the "Name Model"

### ISSUE THREAD

**Issue by danielemorra98** [dfki-ric/phobos#269]
I found out the same error in #220 with the same output printed on the Blender terminal.

**Desktop**
 - OS: Ubuntu 20.04
 - Blender Version 3.4

**Additional context**
When used on Blender2.9 with Phobos cloned at the branch _blender2.9_, it runs seamlessly

**Comment by hwiedPro** [comment]
Thanks for your report. We will make sure that this is solved in phobos v2.0.0. Please note that we can only support blender LTS versions (currently 3.3)

**Comment by hwiedPro** [comment]
Closing this as it runs on LTS3.3 (with version pre_v2.0.0) and LTS2.9 with version 1.0.3
