### ISSUE TITLE
[pre_v2.0.0] Create links don't work for Location: Selected Objects

### ISSUE THREAD

**Issue by brothermechanic** [dfki-ric/phobos#277]
**Describe the bug**
Create links work only for Location: 3d Cursor
Create links don't work for Location: Selected Objects

**To Reproduce**
1. Run bpy.ops.phobos.create_links() ("Create Links")
2. Select location as Selected Objects
```python
Error: Python: Traceback (most recent call last):
  File "~/.config/blender/3.5/scripts/addons/phobos/blender/operators/editing.py", line 1972, in execute
    modellinks.deriveLinkfromObject(
  File "~/.config/blender/3.5/scripts/addons/phobos/blender/model/links.py", line 70, in deriveLinkfromObject
    link = createLink({'scale': scale, 'name': linkname, 'matrix': obj.matrix_world})
NameError: name 'createLink' is not defined
```

**Expected behavior**
In Phobos v1 it works

**Desktop:**
 - OS: Gentoo
 - Version: ~amd64

**Comment by hwiedPro** [comment]
Thanks for the report, this should be fixed. Please test and reopen if the issue reoccurs
