### ISSUE TITLE
[pre_v2.0.0] Create links by "selected object" depend on the size of the object

### ISSUE THREAD

**Issue by brothermechanic** [dfki-ric/phobos#283]
**Describe the bug**
"Create Links" button created 1m size Armature bone every time

**To Reproduce**
1. Select object
2. Push "Create Links" (bpy.ops.phobos.create_links()) by "selected object"
3. There is bone 1m 

**Expected behavior**
It will be cool to have bone size depend on the size of the object. May be depended by boject's bounding box.

**Screenshots**
![Screenshot_20230510_145122](https://github.com/dfki-ric/phobos/assets/3109995/847c7bce-78b5-4ab1-a283-3a7beeab7741)

**Comment by hwiedPro** [comment]
Currently it's created on the objects scale/the size of the visuals. I think in your case the box is not yet a visual. Please try to make it a visual first and then create the link from it. Please let me know if it works as expected.

**Comment by brothermechanic** [comment]
I'm talking about that big bones

https://github.com/dfki-ric/phobos/assets/3109995/b9de0a4c-d18d-4170-96ee-63c2bd8173b7

**Comment by brothermechanic** [comment]
test model
[test_model.zip](https://github.com/dfki-ric/phobos/files/11449920/test_model.zip)

**Comment by hwiedPro** [comment]
Thanks for the video, The way you did it is absolutely correct. This seems to be a bug then.
I had a quick look:
The creation happens here: https://github.com/dfki-ric/phobos/blob/pre_v2.0.0/phobos/blender/model/links.py#L46
And currently the scaling happens only when createLink is called (e.g. when importing from file): https://github.com/dfki-ric/phobos/blob/pre_v2.0.0/phobos/blender/io/phobos2blender.py#L221

It would be nice to have this functionality similarly in deriveLinkFromObject. Do you want to give it a try to fix this?

**Comment by hwiedPro** [comment]
Solved with [1bb14ae](https://github.com/dfki-ric/phobos/commit/1bb14aef829329683b23667c649861ac315ba466)
