### ISSUE TITLE
Install Phobos addOn with Blender v3.5.1 ko

### ISSUE THREAD

**Issue by yvanblanchard** [dfki-ric/phobos#285]
The latest Phobos version seems to not install properly with last Blender version 3.5.1.
Could you please help ?

**Comment by hwiedPro** [comment]
As you can see in the releases notes Phobos v1.0.3 is made for  blender versions > 2.79 < 3.
However, feel free to try the pre_v2.0.0 branch which should work on 3.5.1, and open issues for any bug you might encounter so we can fix it before releasing v2.
