### ISSUE TITLE
I can't find version 2.0.0.

### ISSUE THREAD

**Issue by ogokparty** [dfki-ric/phobos#316]
I can't find the 2.0.0 version in my branch/tag/release.
I can only find the pre_v2.1.0 version.
I was wondering where I could get the phobos.zip file for the 2.0.0 version.

**Comment by 23pointsNorth** [comment]
Managed to figure it out. 

Zip the inner phobos folder of this repo (that contains blender, ci, core, etc..) and use that as the install asset.
