### ISSUE TITLE
Wrong load in 1.0.3 in blender2.93

### ISSUE THREAD

**Issue by wungsui** [dfki-ric/phobos#318]
I use blende(2.93) and photos(1.0.3) in windows and I load a urdf of franka panda robot like this
![image](https://github.com/dfki-ric/phobos/assets/114404451/0baa367b-b200-485d-bdef-b4f4a95dbf3d)
but it came out to this:
![image](https://github.com/dfki-ric/phobos/assets/114404451/f023f9f3-4a7d-4e2f-8413-167ee2e20a86)
it seems to the visual model and collision model are same,but in its urdf,it is:
![image](https://github.com/dfki-ric/phobos/assets/114404451/8451550f-73e1-43b0-91bb-93cbf54be42a)
the .dae and the .stl file is very different,then,I import all the .dae file and export to .stl file,and edit the urdf to this:
![image](https://github.com/dfki-ric/phobos/assets/114404451/27a88c82-1a20-4757-a8cb-1f9aabbd3696)
it seems to it has no color like this:
![image](https://github.com/dfki-ric/phobos/assets/114404451/6d84379e-136e-4f51-983e-c0ef9f78682f)

**Comment by hwiedPro** [comment]
Have you also tried this with the current master (v2.0.0)

**Comment by hwiedPro** [comment]
Closing this as this relates to an older no longer maintained version of phobos.
