### ISSUE TITLE
IMU sensor doesn't get exported

### ISSUE THREAD

**Issue by 23pointsNorth** [dfki-ric/phobos#331]
**Describe the bug**
Create a link, joint and add an IMU sensor to the link.
Export to SDF.
Resulting SDF doesn't contain the IMU sensor.

**Expected behavior**
The SDF to have the sensor IMU tag.

**Comment by hwiedPro** [comment]
Hi @23pointsNorth ,
please check whether [c9f5bec](https://github.com/dfki-ric/phobos/commit/c9f5beca7d69e5fc3033e44d7ae901dc8cf5dc9e) solves this issue

**Comment by hwiedPro** [comment]
I consider this as closed.
