### ISSUE TITLE
Link pose not exported in SDF

### ISSUE THREAD

**Issue by svepe** [dfki-ric/phobos#339]
**Describe the bug**
When an SDF is exported the link pose is no longer set. Previous version of phobos did put a `<pose>` tag relative to the parent joint, but this is no longer the case. 

**To Reproduce**
1. Export SDF from the attached .blend file which contains a simple example with only 2 links.
[excavator_phobos_issue.blend.zip](https://github.com/dfki-ric/phobos/files/12892131/excavator_phobos_issue.blend.zip)
![Screenshot from 2023-10-13 12-50-51](https://github.com/dfki-ric/phobos/assets/3459505/5667499f-b97a-40d3-8404-b7175f022b13)

2. Open the SDF in gazebo
3. Both links are shown at the world origin (0, 0, 0)
![Screenshot from 2023-10-13 12-48-39](https://github.com/dfki-ric/phobos/assets/3459505/61a24dfb-8121-4cab-ba2e-954d4614ba8b)

**Expected behavior**
The second link should be above the first one.

Adding the following line to the second link in the SDF fixes the issue
```
<link name="cabin_link">
    <pose relative_to="cabin_joint">0.00000 0.00000 0.00000 0.00000 0.00000 0.00000</pose>
   ...
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Blender version: 3.6.4
 - At latest phobos commit 56d46c71
 
 Previous versions of phobos did not have this issue.

**Comment by hwiedPro** [comment]
Hi @svepe,
please checkout the commit I just pushed and whether it fixes your issue. ;)

**Comment by skrymets** [comment]
@hwiedPro , well, I've applied the changes ypou've mentioned to my local Blender Phobos addon setup, and it seems, than it does the trick for me.

Thank you! 

PS: The only note that is worth to make - it doesn't work (in some other way - correct position but wrong orientation) IF, let's say, you've added a link (joint), then rotated it for some angle and applied the rotation transformation.

**Comment by AlpenAalAlex** [comment]
> PS: The only note that is worth to make - it doesn't work (in some other way - correct position but wrong orientation) IF, let's say, you've added a link (joint), then rotated it for some angle and applied the rotation transformation.

@skrymets Can you explain this in further detail in a new issue?
