### ISSUE TITLE
Custom property export does not work as expected

### ISSUE THREAD

**Issue by kavonszadkowski** [dfki-ric/phobos#57]
There is a problem with the export of type-specific properties (the second category described on the Wiki's Import/Export page. They seem to vanish, at least in some cases.

Collision information might be overwritten by the hardcoded export of collision bitmasks to *_collision.yml, not sure what might cause the problem for visuals. Some test cases are needed here, as well as a generic solution that warns the user and/or refuses to overwrite files upon export, so that doubled file names are avoided.

**Comment by SamuelYaron** [comment]
Is this issue still 'active'?

**Comment by Amudtogal** [comment]
Probably fixed already, I can't reproduce this error...
