### ISSUE TITLE
Scaled objects exported to SMURF are scaled in MARS too

### ISSUE THREAD

**Issue by ChrisStil** [dfki-ric/phobos#60]
When someone wants to export a robot model to SMURF with Phobos, and some meshes or links have a scale value other than 1.0 (in the Transform panel), The model loaded in MARS is scaled too. That can be confusing because the model that we see in Blender can be completely different from the model seen in MARS.

![screenshot from 2015-05-21 15 07 55](https://cloud.githubusercontent.com/assets/12545069/7749141/35b4000a-ffcb-11e4-81ad-452606fe9b09.png)

For the moment, selecting all objects and using the shortcut CTRL-A -> Scale before the export is the only solution to this problem.

**Comment by kavonszadkowski** [comment]
From the top of my hat, I'm not sure whether this is solely an issue with Phobos, but (or only) a problem in MARS. We'll have to check that.

**Comment by Amudtogal** [comment]
I assume this has been fixed by now.
If other issues arise, please reopen this Issue.
